# Generated by Django 5.2.12 on 2026-07-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_filefavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewarContact',
            fields=[
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.partner',),
        ),
    ]
