# Generated by Django 5.2.12 on 2026-07-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewar_extension', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JewarContact',
        ),
    ]
