# Generated by Django 5.2.12 on 2026-08-13 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jewar_extension', '0002_delete_jewarcontact'),
        ('whatsapp', '0019_whatsapptemplate_is_editing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildGroupsWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('batch_hint', models.CharField(max_length=64, verbose_name='Batch name')),
                ('group_size', models.PositiveIntegerField(default=250, verbose_name='Group size')),
                ('exclude_suppliers', models.BooleanField(default=True, verbose_name='Exclude suppliers')),
                ('dedupe_handsets', models.BooleanField(default=True, verbose_name='Split repeated numbers')),
                ('exclude_meta_errors', models.BooleanField(default=True, verbose_name='Exclude Meta errors')),
                ('exclude_templated_this_month', models.BooleanField(default=False, verbose_name='Exclude contacts already sent a template this month')),
                ('exclude_any_previous_batch', models.BooleanField(default=False, verbose_name='Exclude contacts in any previous batch')),
                ('exclude_specific_batch', models.BooleanField(default=False, verbose_name='Exclude contacts in a specific batch')),
                ('exclude_batch_hint', models.CharField(blank=True, default='', max_length=64, verbose_name='Batch name to exclude')),
                ('total_contacts', models.IntegerField(default=0)),
                ('unique_phones', models.IntegerField(default=0)),
                ('removed_excluded_accounts', models.IntegerField(default=0)),
                ('removed_suppliers', models.IntegerField(default=0)),
                ('removed_previous_batches', models.IntegerField(default=0)),
                ('removed_sent_this_month', models.IntegerField(default=0)),
                ('removed_meta_errors', models.IntegerField(default=0)),
                ('removed_duplicates', models.IntegerField(default=0)),
                ('final_contacts', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('excluded_accounts', models.ManyToManyField(blank=True, related_name='+', to='whatsapp.whatsappaccount', verbose_name='Exclude accounts')),
            ],
            options={
                'verbose_name': 'Build WhatsApp Groups',
                'verbose_name_plural': 'Build WhatsApp Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupBuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('batch_hint', models.CharField(max_length=64, verbose_name='Batch name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Options')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total contacts')),
                ('processed_records', models.IntegerField(default=0, verbose_name='Processed')),
                ('groups_created', models.IntegerField(default=0, verbose_name='Groups created')),
                ('result_message', models.TextField(blank=True, default='', verbose_name='Result')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'WhatsApp Group Build',
                'verbose_name_plural': 'WhatsApp Group Builds',
                'ordering': ['-id'],
            },
        ),
    ]
