# Generated by Django 5.2.12 on 2026-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_user_is_owner'),
        ('crm', '0014_lead_ctwa_clid'),
        ('jewar_extension', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildgroupswizard',
            name='lead_stages',
            field=models.ManyToManyField(blank=True, related_name='+', to='crm.stage', verbose_name='Only contacts whose latest lead is in these stages'),
        ),
        migrations.AddField(
            model_name='buildgroupswizard',
            name='removed_no_stage_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildgroupswizard',
            name='removed_no_tag_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildgroupswizard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='base.tag', verbose_name='Only contacts with these tags'),
        ),
    ]
